### ISSUE TITLE
[RFE] Order alphabetically tenants with AS3 and app in config explorer

### ISSUE THREAD

**Issue by rjouhann** [f5devcentral/vscode-f5#102]
The list of tenants is not sorted alphabetically when using AS3 on BIG-IP or BIG-IQ. Could we get it sorted alphabetically?

Example with BIG-IQ (but AS3 alone on BIG-IP is the same):

![image](https://user-images.githubusercontent.com/25542366/106200688-32b4bd00-616c-11eb-8554-c698cb7bcb5e.png)

For BIG-IQ, it would be good also to order the BIG-IP IP addresses (in example above .183 first, then .184, finally .187).

Same for Apps in Config explorer when loading a qkview or config file. Could we also order alphabetically there?

**Comment by rjouhann** [comment]
@DumpySquare I noticed the same in Apps in Config explorer when loading a qkview or config file. Could we also order alphabetically there?

**Comment by DumpySquare** [comment]
all the lists in as3 view should now be ordered alphabetically.

![image](https://user-images.githubusercontent.com/3260966/107435926-71def880-6af2-11eb-8f65-9e9c42f80181.png)
