### ISSUE TITLE
[RFE] Retrieve the list of all AS3 tenant belonging to a BIG-IP managed by BIG-IQ

### ISSUE THREAD

**Issue by rjouhann** [f5devcentral/vscode-f5#103]
As discussed before, it would be very helpful the have an option for users to export all the AS3 declarations with all the tenants from a BIG-IP. Maybe click right on the target would give an option to export all AS3 config from that device.

![image](https://user-images.githubusercontent.com/25542366/106201093-cb4b3d00-616c-11eb-95af-38e8f809406a.png)

**Comment by DumpySquare** [comment]
feature implemented in v2.10

![image](https://user-images.githubusercontent.com/3260966/107435844-4fe57600-6af2-11eb-9834-0e2ac73d311c.png)
