### ISSUE TITLE
[RFE] Display number of each classes in AS3 declaration

### ISSUE THREAD

**Issue by rjouhann** [f5devcentral/vscode-f5#104]
Provide a feature where users would click right on a JSON file containing an AS3 declaration and provide a summary of the number of classes defined in the declaration.

Example:
Tenant: 5
Application: 10
...

This would help to know quickly how many Tenants or Apps or any other objects defined in an AS3 declaration and avoid the need to use CTL+F and search to count.

**Comment by DumpySquare** [comment]
feature added in v2.10

![image](https://user-images.githubusercontent.com/3260966/107435580-f41aed00-6af1-11eb-9c0f-a2bb5d882d3c.png)
