### ISSUE TITLE
[rfe] Sort alphabetically Sources files in config explorer 

### ISSUE THREAD

**Issue by rjouhann** [f5devcentral/vscode-f5#110]
Could we also sort alphabetically Sources files in config explorer?

<img width="292" alt="Screen Shot 2021-02-18 at 9 04 31 AM" src="https://user-images.githubusercontent.com/25542366/108393395-74afac80-71c8-11eb-8d25-97d7c1a3f4da.png">

Thanks!

**Comment by DumpySquare** [comment]
Good idea.  Will get this one into the next release

**Comment by DumpySquare** [comment]
done.  will be part of next release
