### ISSUE TITLE
[RFE] CF support + fast template

### ISSUE THREAD

**Issue by DumpySquare** [f5devcentral/vscode-f5#112]
Produce support for ATC cloud-failover, including:
- API endpoints like AS3/DO/TS
  - /info
  - /inspect
  - /declare
  - /trigger
  - /reset
- rpm mgmt
  - display CF versions
  - download selected CF version
  - install selected CF version
- FAST template to assist with CS declarations

issue for f5-conx-core api workflows support
https://github.com/DumpySquare/f5-conx-core/issues/8

**Comment by snowblind-** [comment]
+1 Much need!

**Comment by caliraftdude** [comment]
+1

**Comment by itlinux** [comment]
+1

**Comment by DumpySquare** [comment]
Is there a udf or lab for TS I can run through to learn/dev/test against?

**Comment by DumpySquare** [comment]
all this is done except for the fast template.  I think the ATC team was working on one.  Closing.  can open another for the fast template as needed
