### ISSUE TITLE
Closing an "Untitled-1" editor causes the editor to re-launch

### ISSUE THREAD

**Issue by walterk82** [f5devcentral/vscode-f5#119]
While in the the "F5" view...

If there is an editor that is not saved and you try to close it out... you can't as the editor immediately re-launches.

https://user-images.githubusercontent.com/5244553/110676896-80c4d380-81a2-11eb-8c0b-e92e94e3ae25.mp4

**Comment by DumpySquare** [comment]
Hey Walter, this is interesting.  Can you reboot your computer to see if this continues?

**Comment by walterk82** [comment]
I don't have to go that far, if I close VS code (and reopen), the editors return, but then I can close them from the standard files view.

**Comment by walterk82** [comment]
I just re-produced the issue by doing File -> New from the F5 view.  The trick is that you have to have an editor opened (with a disk backed file) from the explorer view first.

**Comment by DumpySquare** [comment]
ok.  thanks.  so, did you reboot your computer?

**Comment by walterk82** [comment]
Yes, this morning.

**Comment by walterk82** [comment]
It was discovered that a different plugin "codetogether" is causing this issue.  Thank-you for looking at this.
