### ISSUE TITLE
[RFE] Ability to identify device as BIG-IQ/BIG-IP in the F5 Hosts

### ISSUE THREAD

**Issue by rjouhann** [f5devcentral/vscode-f5#122]
It would be great to be able to identify the type device as BIG-IQ/BIG-IP/NGINX controller (in the future? :D) in the F5 Hosts

**Comment by DumpySquare** [comment]
got this in.  with deeper tooltip information

![image](https://user-images.githubusercontent.com/3260966/111921527-14c85200-8a63-11eb-872c-9ebc3b95f938.png)
