### ISSUE TITLE
[RFE] Provide ability to edit the bigip config file from the editor, save and reload config

### ISSUE THREAD

**Issue by rjouhann** [f5devcentral/vscode-f5#124]
Another very useful feature to help with migration of config from different platforms would be to add the capability to edit and save the bigip config files extracted in the config explorer on the BIG-IP and provide ability to do a **tmsh load sys config** to test the config modified.

The workflow would be:
1. Explore config
2. open one of the big-ip config file (/config/bigip.conf or bigip_base.conf, ..)
3. make a change
4. save it (take a backup of the modified file with the date in the filename)
5. provide option for the user to load the config and see result in the output terminal

**Comment by walterk82** [comment]
Is there currently a way to SSH to the box now?  I would be concerned about failure management if you were to lock yourself out.

**Comment by DumpySquare** [comment]
@rjouhann The ``F5: Merge TCL/TMOS`` command might cover this use case.  The command takes the text in the editor, copies to the F5 and attempts to merge it with the running config via "tmsh load sys config file <filename>".  If successful, just a little notification, but if it fails, it will show the full error response in a new editor window.

The same workflow is used for iRules and iApps.  See the ``Config Migration`` at the bottom.

https://f5devcentral.github.io/vscode-f5/#/tcl

@walterk82 there is the ability to configure the extension automatically ssh to the connected device via onConnect/onDisConnect.  Would this help your use case?
https://f5devcentral.github.io/vscode-f5/#/utilities?id=onconnectondisconnect-commands

**Comment by DumpySquare** [comment]
had a chat with Roman and the Merge TCL/TMOS command fits his use case
