### ISSUE TITLE
[RFE] Add capability to update AS3/DO on BIG-IQ similar to BIG-IP

### ISSUE THREAD

**Issue by rjouhann** [f5devcentral/vscode-f5#125]
RFE in the title, here are some details on how to do it on BIG-IQ

https://support.f5.com/csp/article/K54909607

Also note not all the versions of AS3 and DO are supported when they get released even though PD is doing his best to verify each release. It might be a good idea to refer to the above KB somewhere to ask the user to check if the version he is trying to install on IQ is supported.

**Comment by DumpySquare** [comment]
good idea, I think we might be able to squeeze this into the bigiq v1, but wanted to talk with you about layout and potentially breaking out the new Hosts V2 functionality to it's own window like the bigiq stuff.  Kinda keep things modular in hope of not cluttering things too much.
