### ISSUE TITLE
[RFE] Confirmation prompt before posting a declaration

### ISSUE THREAD

**Issue by fustilarian01** [f5devcentral/vscode-f5#132]
Similar to the prompt that pops up when you try to close a file without saving your changes, it would be helpful to have a prompt that would show which BIG-IP you are connected to and ask for confirmation before sending the configuration along. This would help address two issues:

1. There is no safety check in place to make sure you are posting the configuration to the correct BIG-IP
2. I have dark mode enabled in VS Code, and the selection indicator in the server list is only slightly brighter than the GUI background, thus is can be very difficult at a glance to tell which BIG-IP I am connected to.

I could see how having to OK every configuration deployment might be a little annoying to some, so there could be an option added to the prompt to keep it from showing up again. But even if a confirmation prompt is a little annoying, it would certainly be a lot less annoying than dealing with the fallout from knocking a few hundred production applications offline by posting the wrong configuration to a production BIG-IP. :)

**Comment by DumpySquare** [comment]
Hi @fustilarian01!  Thanks for opening this feature request.  

The intent for this tool was to be used for development in a non-production environment.  The outcomes/output of this tools would then be used in production automation flows.  

With that being said, we totally get that everyone is at different phase in their automation journey and there is a ton of value in using this tool in any environment, including production.

Given the choice, would you rather have a more obvious "connected" indicator in view somewhere or would you still prefer to have a pop-up/confirmation box?

**Comment by gaetanquentin** [comment]
a pop-up confirmation box would be better.

**Comment by fustilarian01** [comment]
Hi there, 
Is this enhancement in the works for a future upgrade? I use the F5 extension frequently, and I always have to triple check to make sure all of the settings are correct before deploying the AS3 configuration. A confirmation box would be extremely helpful. 
Thanks!

**Comment by DumpySquare** [comment]
done.  pending v3.4.0 release.  enable prompt in settings

![image](https://user-images.githubusercontent.com/3260966/150221112-daa0e2b7-7c83-4171-995c-570406c00367.png)

![image](https://user-images.githubusercontent.com/3260966/150220996-c3ba6cab-3d15-4abb-8232-cba1e5d76c03.png)
