### ISSUE TITLE
DEPTH_ZERO_SELF_SIGNED_CERT - self signed certificate

### ISSUE THREAD

**Issue by jmcalalang** [f5devcentral/vscode-f5#133]
I'm receiving an error from the vscode extension that I have a self-signed cert. This is true. However, it hasn't been an issue in the past. It appears like someplace I need to tell the extension to ignore the ca error. I looked through the documentation and couldn't find where to find this.

Version: v2.10.7
VSCode: 1.55.0

Doc lookup:
![doc](https://user-images.githubusercontent.com/20847865/113933013-ee1b5280-97a8-11eb-8297-9f684a3601f2.png)

Error:
![error](https://user-images.githubusercontent.com/20847865/113933045-f83d5100-97a8-11eb-836b-888902e962d0.png)

**Comment by DumpySquare** [comment]
thank you for this issue!  

So, i think an os update happened that changed how the node process handles self-signed certs.  I've had a couple of other people run into the same problem.  The latest beta of v3.0 has the fix baked in.  Will provide a config switch to manage this in the future.

https://github.com/f5devcentral/vscode-f5/releases/tag/v3.0.0-beta.11

**Comment by DumpySquare** [comment]
- Seems to be an OS update that changed how the underlying node process handles self-signed certs
  - Axios is configured to handle self-signed, but this was still happening
  - NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' seems to have fixed for now
  - will add a config switch in the future
