### ISSUE TITLE
[RFE] Add ability to follow DO tasks on BIG-IQ

### ISSUE THREAD

**Issue by rjouhann** [f5devcentral/vscode-f5#135]
When using DO with BIG-IQ, it would be great to follow the DO onboarding tasks from the VS code.

Example of what the BIG-IQ shows:
<img width="1024" alt="Screen Shot 2021-04-15 at 10 33 26 PM" src="https://user-images.githubusercontent.com/25542366/114976361-b2345d00-9e3a-11eb-8e0b-bde6926502c3.png">

I was thinking maybe under the new BIG-IQ section, having an Onboarding entry where user could see the tasks status and could handover on it to see the status.

**Comment by DumpySquare** [comment]
Good idea!  Do we have any postman work flows or do I need to discover this through the UI?
