### ISSUE TITLE
[RFE] certificate authentication for BIG-IP/BIG-IQ

### ISSUE THREAD

**Issue by grf5** [f5devcentral/vscode-f5#136]
I'd like to be able to use a certificate to connect to the BIG-IP/BIG-IQ through the vscode extension.

**Comment by DumpySquare** [comment]
Hi @grf5, thanks for opening this RFE.  Can you provide any examples of this?  Any scripts or solutions that I could reference?

**Comment by grf5** [comment]
The BIG-IP can be configured to use SSH keys for authentication per https://support.f5.com/csp/article/K13454. I do not see an option within VS Code to use SSH keys for authentication within FAST. I would like to use this versus password auth so that I can more easily connect to cloud deployments where allowing password authentication is too risky. Thanks!

**Comment by DumpySquare** [comment]
Hey Greg, this vscode extension only support rest API based connectivity, not ssh.

Can  you help me understand what kind of workflows your using (AS3, irules, ATC rpm mgmt/...)?

**Comment by grf5** [comment]
Ben, this came up during testing with UDF. I cannot figure out how to authenticate to the BIG-IP with the extension when deployed within UDF.

**Comment by DumpySquare** [comment]
Had some side comms about UDF access methods.  Mainly the use of coder.  Will follow up in a couple of days to see if there are any other questions before closing.

**Comment by DumpySquare** [comment]
Talked with requestor, everything good to close.
