### ISSUE TITLE
[RFE] merge TCL/TMOS pool member only adds to existing config

### ISSUE THREAD

**Issue by silliw-nhoj** [f5devcentral/vscode-f5#137]
The merge TCL/TMOS feature doesn't reflect the desired state when attempting to modify pool member configs (ie. modifying port numbers or deleting members). 

For example if the below pool were modified to change the member port number to 8083, the result would be two members. One w/ port 8083 and the other w/ 8084. The issue seems to be with the **tmsh load sys config merge <file>** command. I've tested the **tmsh load sys config replace <file>** command and this seems to work as expected to update the pool with the desired state.

```
ltm pool /Common/demo_http {
    members {
        /Common/10.3.110.10:8084 {
            address 10.3.110.10
        }
    }
}
```

**Comment by silliw-nhoj** [comment]
Thanks Ben. BTW - I locally updated the command in **tclTreeProvider.js** to replace instead of merge and it looks like it's working well.

**Comment by DumpySquare** [comment]
this has been added in the pending v3.5 release
