### ISSUE TITLE
[RFE] Convert tmsh configuration to AS3

### ISSUE THREAD

**Issue by raZorTT** [f5devcentral/vscode-f5#142]
Hi

I was wondering if there was any plans to include the F5 AS3 Configuration Converter or tmsh2JSON into the extension?

https://github.com/f5devcentral/f5-as3-config-converter/

https://github.com/johnalam/tmsh2JSON 

It'd be brilliant if we could take a conf file generated using Multi-App select and then convert that to AS3. Be a great way to migrate some of the older deployments to AS3.

Cheers,
Simon

**Comment by raZorTT** [comment]
Thanks @DumpySquare,

I will check it out :D

**Comment by raZorTT** [comment]
Hey @DumpySquare 

Great work on the video!

I updated to 3.0.1, but I don't get the convert with ACC option when I right click? Do I need another extension installed to enable the option?

Cheers
Simon

**Comment by DumpySquare** [comment]
Yes, install both the vscode-f5-chariot and vscode-f5 extensions.

Chariot must be downloaded from the repo:  https://github.com/f5devcentral/vscode-f5-chariot. 

We are working to publish to marketplace soon

**Comment by raZorTT** [comment]
Getting closer! I tried to build the package and installed vsix. I get the option now when I right click, but nothing happens. Any thoughts? Are there any logs I can look at why it might be failing?

    npm install -g vsce
    npm install typescript
    cd ..\vscode-f5-chariot-main
    vsce package

    DONE  Packaged: H:\repo\vscode-f5-chariot-main\vscode-f5-chariot-1.11.0.vsix (109 files, 1.5MB)

**Comment by raZorTT** [comment]
Thanks. I downloaded the vsix from the latest release and it works brilliantly!!

**Comment by mdditt2000** [comment]
@raZorTT good to hear. If you have any issues with the conversion please use https://github.com/f5devcentral/f5-as3-config-converter/issues TY
