### ISSUE TITLE
Fail to explore config on connected BIG-IP

### ISSUE THREAD

**Issue by silliw-nhoj** [f5devcentral/vscode-f5#143]
Hi,

I was seeing the same issue as #109 and I don't think it's related to UCS file size. The debug message (below) indicates that **tempFile** variable isn't being converted.
`
building mini_ucs on device with following command over bash api: tar -czf /shared/images/**${tempFile}** /config/bigip.conf /config/bigip_base.conf /config/partitions
`

I was able to get it working by changing line 47 in cfgExplorer.js to enclose the command in backticks instead of straight single quotes.

Thanks!
John

_Originally posted by @silliw-nhoj in https://github.com/f5devcentral/vscode-f5/issues/109#issuecomment-833140300_

**Comment by DumpySquare** [comment]
Hey John, sorry to hear your still having problems.  What version of the extension are you running?

With v3.0, that was just released, that functionality got moved to here (and got rewritten):  https://github.com/DumpySquare/f5-conx-core/blob/399381f0696c5d14618ea749bb3f3a79cd84a673/src/bigip/ucsClient.ts#L121

if you want I can reach out direct and we can dive a bit deeper.

**Comment by silliw-nhoj** [comment]
Thanks Ben! I've been running v2.10.7. It's since auto-updated to version 3.0.1 a couple of days ago with no issues.
