### ISSUE TITLE
[RFE] app.conf editor doesn't scroll back to the top on selection of new app

### ISSUE THREAD

**Issue by raZorTT** [f5devcentral/vscode-f5#144]
Hi

Being a bit pedantic, but thought i'd log it 

Steps to reproduce.
1. Import .conf file
2. Select an app to view with a large number of components
3. Focus the newly open app.conf window
4. Scroll down to the bottom of the file
5. Under the config explorer pane, select another app.

The updated app.conf window stays at the previous line number, or moves to the end if the config isn't as big.

Cheers
Simon

**Comment by DumpySquare** [comment]
Hi @raZorTT, I've noticed this also.  I think there is a command to scroll to the top of the screen.  I can probably add that as part of the editor rewrite, or it might be a non-issue as we transition these files to a virtual file system.  Changing this to an RFE for future work

**Comment by DumpySquare** [comment]
Configured this render to scroll to top as requested.  released in v3.5
