### ISSUE TITLE
cannot open untitled:app.conf. Detail: file already exists

### ISSUE THREAD

**Issue by raZorTT** [f5devcentral/vscode-f5#145]
Hi

Steps to reproduce.
1. Import .conf file
2. Select an app to view 
3. Focus the newly open app.conf window
4. Ctrl + s to save
5. Under the config explorer pane, select another app.

```
ERROR: unhandledRejection Error: cannot open untitled:app.conf. Detail: file already exists
    at file:///C:/Users/auser/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2290:64031
```

Doing the default save creates a c:\app.conf which needs to be deleted before you can view any more apps.

Cheers,
Simon

**Comment by DumpySquare** [comment]
Hi @raZorTT.  Thanks for bringing this to our attention.  Interesting workflow. 

These configs, at this point, typically don't need to be saved, but converted to as3, then potentially saved.  Either way, we recommend saving the configs to unique files/destinations.

we just implemented a virtual file system with the vscode-nim extension for managing config files.  This is a much better system of holding files and providing typical document life cycle for CRUD operations like this.   So, this should get better in the future.

**Comment by raZorTT** [comment]
Hi @DumpySquare 

Totally agree, I hadn't managed to get ACC installed at the time and was looking to break the config file into grouped apps. and just saved assuming it would bring up the save dialog.

As you say the configs would normally be saved off to a unique destination :)

**Comment by DumpySquare** [comment]
cool.  ACC-chariot is now on the marketplace, so you can easily access it.  do you want to keep this open or are we good with knowing there are plans to make this better in the future?

https://marketplace.visualstudio.com/items?itemName=F5DevCentral.vscode-f5-chariot

**Comment by raZorTT** [comment]
Happy to close :)
