### ISSUE TITLE
ATC uninstall option does not show up

### ISSUE THREAD

**Issue by vbojko** [f5devcentral/vscode-f5#150]
### Environment
 * Application Services Version: 3.1.0
 * BIG-IP Version: 16.0.1 and 15.1.2.1

### Summary
I want to uninstall ATC rpms via the VS Code Extentions. 
after "F1" and starting to type: "f5: U" the option for Un-Install does not show up.

### Steps To Reproduce
1. connect to BIG-IP

2. type "F1"
3. type: "f5: U"

### Expected Behavior
the Un-Install option should show

### Actual Behavior

<img width="875" alt="Screen Shot 2021-10-12 at 8 55 08 PM" src="https://user-images.githubusercontent.com/16340599/137065390-77c6a480-fdeb-4f25-9d1c-7011ff39a963.png">

**Comment by IkueMoto** [comment]
It may be related but it seems like "Install RPM" is also not working.  It's available but doesn't do anything when you click on it.

**Comment by DumpySquare** [comment]
Can that computer get to the internet?    When you first launch vscode/extension, there should be some logs in the OUTPUT that should talk about updating ATC metadata.  Can you provide those logs?

**Comment by DumpySquare** [comment]
@vbojko I am seeing the new un-install button in the BIG-IP view.  Is this what you are looking for?

![image](https://user-images.githubusercontent.com/3260966/143773628-8451d5a6-e7d4-4b8b-a5ba-b3f6484c7f25.png)
