### ISSUE TITLE
Multi-App Select not working

### ISSUE THREAD

**Issue by BarryHaines** [f5devcentral/vscode-f5#160]
Currently running v3.3.0 of the vscode F5 extension and the config explorer multiple app selection is no longer working.  If I select multiple virtual server the show apps menu with the right click mouse selection is not available anymore and only one virtual servers configuration is listed in the main menu.  I have also notice in the config explorer the branch menu is now partitions and not Apps, I don't know if this has caused the issue.

https://f5devcentral.github.io/vscode-f5/#/config_explorer?id=multi-app-select

**Comment by DumpySquare** [comment]
@BarryHaines, thanks for opening this.  I think you are correct.  I'm wrapping up some other features and can get this fixed in the next release.

**Comment by DumpySquare** [comment]
Fixed.  Pending v3.4.0 release
