### ISSUE TITLE
[RFE] Add support to declare API Protection profiles

### ISSUE THREAD

**Issue by ustrum** [f5devcentral/vscode-f5#187]
It would be nice to be able to configure API Protection profiles in a declarative fashion

I´m currently trying to develop a service to automatically deploy virtual servers that must have a different API protection profile for each one, and can´t find a way to do it besides direct iControl API requests (and that´s proving hard as the entrypoints are not documented at all)

**Comment by ustrum** [comment]
Wrong repo, sorry

**Comment by DumpySquare** [comment]
Do you have any examples/workflows/APIs you can provide to help me better understand what you are trying do to?  there are several ways to automate things on tmos.

**Comment by ustrum** [comment]
> Do you have any examples/workflows/APIs you can provide to help me better understand what you are trying do to? there are several ways to automate things on tmos.

I´m so sorry, opened the issue under the wrong repo, meant to do it under the f5-appsvcs-extension: https://github.com/F5Networks/f5-appsvcs-extension/issues/636

please close this one, sorry about the inconveniencies...
