### ISSUE TITLE
Usability: Problems window displays stale 'problems'

### ISSUE THREAD

**Issue by GlenWillms** [f5devcentral/vscode-f5#189]
When switching between QKView files and analyzing for XC compatibility, the 'Problems' output window does not get cleared and shows previous problems. 

Clearing this window on config clearing, and providing guidance on XC diag would be helpful.

**Comment by DumpySquare** [comment]
Thanks @GlenWillms!  Looking into this!

**Comment by DumpySquare** [comment]
This should be fixed with the latest v3.8.6 release.  Please confirm

**Comment by DumpySquare** [comment]
XC workflows have been smoothed out and have no issues at this time
