### ISSUE TITLE
wildcard virtuals not being caught by XC Diagnostics

### ISSUE THREAD

**Issue by m-bers** [f5devcentral/vscode-f5#193]
I have a bigip.conf that contains a virtual with a wildcard port. When importing this into the extension, XC Diagnostics does not catch this as problematic, even though wildcard virtuals are not supported in XC. 
```
ltm virtual some_virtual {
    destination /Common/10.1.1.18:0
    ip-protocol tcp
    mask 255.255.255.255
    pool /Common/some_pool
    profiles {
        /Common/tcp { }
    }
    source 0.0.0.0/0
}
```

**Comment by DumpySquare** [comment]
Thanks for opening this issue!  I'll work up a new rule and add it to the next release!

**Comment by DumpySquare** [comment]
I created the following rules to provide errors for wildcard VIPs and wildcard ports.

You can add the following to your current ruleset, but it will also be included in the next release.

```json
    {
        "code": "589b",
        "severity": "Error",
        "title": "Wildcard port on virtual not supported in XC",
        "message": "Wildcard port on virtual not supported in XC",
        "regex": "destination [\/\\w\\.]+:0"
    },
    {
        "code": "74f7",
        "severity": "Error",
        "title": "Wildcard VIP not supported",
        "message": "Wildcard VIP not supported",
        "regex": "destination [\/\\w\\.]+0.0.0.0:\\d"
    }
```
