### ISSUE TITLE
Update IRULES/IAPPS navigation to include icall/tmsh scripts

### ISSUE THREAD

**Issue by jasonrahm** [f5devcentral/vscode-f5#195]
The current IRULES/IAPPS navigation is great, but would appreciate adding tmsh script and icall script/handler/trigger functionality to that list

**Comment by f5-rahm** [comment]
pull request #197 submitted as an example of what I'm looking for

**Comment by DumpySquare** [comment]
features released in v3.10.0 released yesterday
