### ISSUE TITLE
XC Diagnostics Rule: 05ab needs to be more specific. 

### ISSUE THREAD

**Issue by GlenWillms** [f5devcentral/vscode-f5#198]
Currently matching on creation-times with :53 

e.g.:  `creation-time 2021-08-17:14:53:31`

Adjusting the regex line to only match on lines with the text '`destination`' resolves the issue. 

e.g.:
`"regex": "/(?=.*destination)(:(8443|2379|9090|9999|18091|22222|23790|23791|1067|2380|8005|18092|9153|10250|10252|10259|500|8007|10251|18095|23801|5355|8507|9007|68|323|23802|8444|8505|10249|10257|22|4500|8087|18093|53|6443|10256))/si"`

**Comment by DumpySquare** [comment]
Thanks!  added to the next pending release (v3.10.0)
