### ISSUE TITLE
XC Diagnostics - UDP support

### ISSUE THREAD

**Issue by CarlB-dev** [f5devcentral/vscode-f5#207]
When a virtual server with IP-protocol of udp is found, the XC Diagnostics flags it as Red and then shows the problem description of XC does not currently support UDP (0049)

XC does in fact support UDP load balancing via the Virtual Hosts functionality. 

https://docs.cloud.f5.com/docs/how-to/advanced-app-nwg/virtual-hosts

**Comment by CarlB-dev** [comment]
When a virtual server with IP-protocol of udp is found, the XC Diagnostics flags it as Red and then shows the problem description of XC does not currently support UDP (0049)

XC does in fact support UDP load balancing via the Virtual Hosts functionality. 

https://docs.cloud.f5.com/docs/how-to/advanced-app-nwg/virtual-hosts

**Comment by CarlB-dev** [comment]
I updated my local rules file to alter this as follows:
    {
        "code": "0049",
        "severity": "Information",
        "title": "XC UDP LB",
        "message": "XC supports UDP LB under Virtual Host settings. Internal DNS LB is not supported.",
        "regex": "ip-protocol udp"
    },

**Comment by DumpySquare** [comment]
updated in pending v3.12 release.  thank you!
