### ISSUE TITLE
XC Diagnostics - Clone Pools not supported

### ISSUE THREAD

**Issue by CarlB-dev** [f5devcentral/vscode-f5#208]
Currently the functionality provided by clone pools in BIG-IP is not supported in XC.
XC diagnostics does not flag Virtual Servers that have this configuration as not compatible with XC and it should.

Clone pools are commonly used to push traffic to session replay software systems like Tealeaf, GlassBox, Quantum Metric, Hotjar, and FullStory. 

Session Replay Software is a widely used technology, and many people are seeking reliable, secure software solutions with split url testing, data analysis, and search box. 

Snippet of a Virtual Server with this config to be flagged:

`ltm virtual /Common/myVirtual_http{
    clone-pools {
        /Common/SessionReplayTarget-http-Pool {
            context serverside
        }
    }
 `

**Comment by CarlB-dev** [comment]
The following rule is working in my config:
    {
        "code": "5cf0",
        "severity": "Error",
        "title": "Clone Pool detected",
        "message": "Clone Pool functionality is not supported.",
        "regex": " clone-pools "
    },

**Comment by DumpySquare** [comment]
added to the pending v3.12 release.  Thank you!
