### ISSUE TITLE
XC Diagnostics - reserved ports not working

### ISSUE THREAD

**Issue by CarlB-dev** [f5devcentral/vscode-f5#209]
XC Diagnostics should flag VS for LB DNS services on TCP/UDP port 53 as not allowed due to reserved ports.
However the Regex is not working to flag virtuals on port 53.

Regex line that needs correction - https://github.com/f5devcentral/vscode-f5/blob/main/diagRules/tmosXcRules.json#L105 

Currently, XC does not support load balancing internal DNS servers, so maybe we make a new rule for the DNS use case.  If LB external DNS we can support this with XC DNS LB, otherwise we cannot.

**Comment by DumpySquare** [comment]
can you provide any of the examples of it working and not working?

**Comment by CarlB-dev** [comment]
New pattern that captures the ranges properly as well as ensuring it doesn't trigger on pool members.

```
    {
        "code": "05ab",
        "severity": "Warning",
        "title": "XC reserved ports",
        "message": "List of reserved ports 22|53|68|323|500|1067|2379|2380|4500|5355|6443|8005|8007|8087|8443|8444|8505|8507|9007|9090|9153|9999|10249|10250|10251|10252|10256|10257|10259|18091|18092|18093|18095|22222|23790|23791|23801|23802|28000-32767|65000-65535",
        "regex": "(?<=\\bdestination\\s\\/\\S+\\/\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}:)(?:2[89][0-9]{3}|3[01][0-9]{3}|32[0-6][0-9]{2}|327[0-5][0-9]|6[5-9][0-9]{3}|65[0-4][0-9]{2}|6553[0-5]|(?:22|53|68|323|500|1067|2379|2380|4500|5355|6443|8005|8007|8087|8443|8444|8505|8507|9007|9090|9153|9999|10249|10250|10251|10252|10256|10257|10259|18091|18092|18093|18095|22222|23790|23791|23801|23802))"
    },

```

Here are two example that the original rule was not capturing:
An internal DNS virtual running on TCP 53
```
ltm virtual /Microsoft-Exchange/pool-int-dns-tcp-53 {
    destination /Microsoft-Exchange/10.175.99.145:53
    ip-protocol tcp
    mask 255.255.255.255
    pool /Microsoft-Exchange/pool-int-dns-53
    profiles {
        /Common/tcp { }
    }

```
This example I modified by hand for testing purposes in a separate conf file.
```

ltm virtual /Common/byoadc-VIP {
    description mylistener.byoadc.com
    destination /Common/157.109.110.76:28010
    ip-protocol tcp
    last-modified-time 2023-04-15:13:23:53
    mask 255.255.255.255
    pool /Common/SSLSUPPORT-POOL
    profiles {
        /Common/byoadc_2024 {
            context clientside
        }
        /Common/http { }
        /Common/tcp { }
    }
```

I will provide full files via internal communications.

**Comment by CarlB-dev** [comment]
This example rule has been working fine for me.
{
        "code": "05ab",
        "severity": "Warning",
        "title": "XC reserved ports",
        "message": "List of reserved ports 22|53|68|323|500|1067|2379|2380|4500|5355|6443|8005|8007|8087|8443|8444|8505|8507|9007|9090|9153|9999|10249|10250|10251|10252|10256|10257|10259|18091|18092|18093|18095|22222|23790|23791|23801|23802|28000-32767|65000-65535",
        "regex": "(?<=\\bdestination\\s\\/\\S+\\/\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}:)(?:2[89][0-9]{3}|3[01][0-9]{3}|32[0-6][0-9]{2}|327[0-5][0-9]|6[5-9][0-9]{3}|65[0-4][0-9]{2}|6553[0-5]|(?:22|53|68|323|500|1067|2379|2380|4500|5355|6443|8005|8007|8087|8443|8444|8505|8507|9007|9090|9153|9999|10249|10250|10251|10252|10256|10257|10259|18091|18092|18093|18095|22222|23790|23791|23801|23802))"
    },

**Comment by DumpySquare** [comment]
CarlB-dev pointed out that my shortened version does not include the port ranges that must be excluded.  So, we will stick with his last suggestion.  This update will be in the pending v3.12 release
