### ISSUE TITLE
System Management IP Declarative Onboarding Conversion is non functional

### ISSUE THREAD

**Issue by MicSkr** [f5devcentral/vscode-f5#224]
### Environment
 * F5 Extension Version: 3.14.0

### Summary
Certain Sys Management configurations do not convert properly

### Steps To Reproduce
1. Convert the following CONF to DO declaration by highlight and right click, convert to DO:
```
sys management-ip 10.10.10.1/24 {   }
```

2. Observe the following error response:
```json
{
    "schemaVersion": "1.0.0",
    "class": "Device",
    "async": true,
    "Common": {
        "class": "Tenant",
        "}": {
            "class": "ManagementIp",
            "address": "}"
        }
    }
}
```

### Expected Behavior
Output like this:
```json
{
    "schemaVersion": "1.0.0",
    "class": "Device",
    "async": true,
    "Common": {
        "class": "Tenant",
        "ManagementIp_IPv4": {
            "class": "ManagementIp",
            "address": "10.10.10.1/24"
        }
    }
}
```

**Comment by DumpySquare** [comment]
this function is provided by the vscode-f5-chariot extension which is based on the ACC engine.  That engine is no longer getting any public updates.  closing
