### ISSUE TITLE
[BUG] password focus away issues

### ISSUE THREAD

**Issue by DumpySquare** [f5devcentral/vscode-f5#228]
@joe-belliveau-WD. I've opened your issues here so I can look into them.

---

## 1. Option to allow selfsigned certs or disable some checks #31
https://github.com/bitwisecook/vscode-iRule/issues/31

SSL Errors is using self signed certificates
to reproduce
-> create an f5 use a self signed cert from the appliance for the management interface
-> bind the cert to interface
-> add the device to the f5 module list
-> Try to connect

cause: [Error: write EPROTO 1305672610496:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:231:

---

## 2. Fix Connecting to single device if a window swap occurs #32
https://github.com/bitwisecook/vscode-iRule/issues/32

When connecting to a device, if you move focus to another window the password prompt is gone and "cancelled" this shouldn't happen. The prompt should remain and able to be filled when focus is returned

---

## 3. Have to restart vscode to attempt to connect to a single device #33
https://github.com/bitwisecook/vscode-iRule/issues/33

When using a single device vscode has to be restarted in order to attempt a new connection to the device

Steps to reproduce > Add device, when asked for password swap off the focused window, return to focused window and try to read the configuration of the device. Connection gets stuck and you have to kill vscode and restart in order to allow another connection attempt.

**Comment by DumpySquare** [comment]
Issue 1 should already be available, my lab has custom device certs.  We may need to talk about how your updating them.
Issue 2; I've made some adjustments to the connect function to enable "ignoreFocusOut" on the password prompt, so it will stay visible while out of focus.  I also added some logic, error handling and logging to the connect function to hopefully make this process a bit smoother.
Issue 3 is probably related to issue 2 and should be resoled with issue 2.

These updates will be in the pending 3.15 release

**Comment by DumpySquare** [comment]
Just released 3.15. that should fix this.  Please confirm

**Comment by joe-belliveau-WD** [comment]
Confirmed fixed.

Thank you!

-Joe

From: Ben Novak ***@***.***>
Date: Thursday, October 26, 2023 at 1:06 PM
To: f5devcentral/vscode-f5 ***@***.***>
Cc: Joe Belliveau ***@***.***>, Mention ***@***.***>
Subject: [External Sender] Re: [f5devcentral/vscode-f5] [BUG] password focus away issues (Issue #228)

Just released 3.15. that should fix this. Please confirm

**Comment by DumpySquare** [comment]
my pleasure!  thanks for using the extension and providing feedback!  closing
