### ISSUE TITLE
September 2023 (version 1.83) fails to load extension

### ISSUE THREAD

**Issue by jmcalalang** [f5devcentral/vscode-f5#229]
The new September release causes the extension to fail:

![image](https://github.com/f5devcentral/vscode-f5/assets/20847865/60577f13-1a2a-4e74-b8be-247dc11b95f8)

Reverting back to August the extension loads successfully.

@DumpySquare @mikeoleary

**Comment by DumpySquare** [comment]
Just released 3.15. that should fix this.  Please confirm

**Comment by DumpySquare** [comment]
@jmcalalang @mikeoleary ; have you had a chance to confirm the latest fix for this issue?

**Comment by jmcalalang** [comment]
Can confirm, I'm upgraded and working.

tested fast/as3
