### ISSUE TITLE
v3.14.0: Failed to activate extension

### ISSUE THREAD

**Issue by jessed** [f5devcentral/vscode-f5#231]
Extension Runtime status is "Not yet activated".
OS: MacOS Ventura 13.5.2
This issue occurred 

Debug tools show the following error:
"
Failed: dlopen(/Users/~username~/.vscode/extensions/f5devcentral.vscode-f5-3.14.0/node_modules/keytar/build/Release/keytar.node, 0x0001): tried: '/Users/~username~/.vscode/extensions/f5devcentral.vscode-f5-3.14.0/node_modules/keytar/build/Release/keytar.node' (**not a mach-o file**)
"

Confirmed that the file is not Mach-O:
"
file keytar.node
keytar.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=49f7c16404c6bc89121aa5d139c6ecbefd491c85, stripped
"

I have uninstalled the extension, manually removed the extension directory, and reinstalled the extension, but the issue persists. Please let me know if additional information is required.

**Comment by DumpySquare** [comment]
Sorry for the problems. This certainly seems to be related to the latest vscode versions.  I'm hearing that version 2.82.3 from April is working.  Might need to go back a little further.  I will be looking into this soon

**Comment by jmcalalang** [comment]
i can confirm the august version is working.

**Comment by jessed** [comment]
I did not realize it was the version of VS Code that you were referring to.
