### ISSUE TITLE
v.3.14 keytar.node is not a valid Win32 application

### ISSUE THREAD

**Issue by Bardo369** [f5devcentral/vscode-f5#232]
I am not sure whether this was due to a windows patch but more or less match with the time that I started to see issues.

These are some logs that I am seeing:

[error] Activating extension F5DevCentral.vscode-f5 failed due to an error:
error] Error: \\?\c:\Users\username\.vscode\extensions\f5devcentral.vscode-f5-3.14.0\node_modules\keytar\build\Release\keytar.node is not a valid Win32 application.
\\?\c:\Users\username\.vscode\extensions\f5devcentral.vscode-f5-3.14.0\node_modules\keytar\build\Release\keytar.node
[f5-ext-v3.14.txt](https://github.com/f5devcentral/vscode-f5/files/12898223/f5-ext-v3.14.txt)
![vscode-f5-ext-error](https://github.com/f5devcentral/vscode-f5/assets/141449218/d421aeeb-9ce3-4154-b7fa-a8d1ce700030)

**Comment by DumpySquare** [comment]
Thanks for opening this issue.  I am looking into this.  In the mean time, people have had success with running vscode v1.82 or earlier

**Comment by Bardo369** [comment]
Thanks! I forgot to mention that my VS Code was on v.1.83. I can confirm the extension works in v1.82.

**Comment by DumpySquare** [comment]
@Bardo369 did the latest release fix your issue?

**Comment by Bardo369** [comment]
Yes! I can see my hosts now.

Thanks, Ben!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DumpySquare** [comment]
resolved.  thank you!
