### ISSUE TITLE
command '' not found

### ISSUE THREAD

**Issue by andreasforseth** [f5devcentral/vscode-f5#244]
When trying to open an AS3 tenant file to look at the configuration deployed to my BIG-IP, I get the following error:

<img width="553" alt="Screenshot 2024-01-04 at 15 37 12" src="https://github.com/f5devcentral/vscode-f5/assets/42814366/de92cf7b-85f8-45ea-8362-22040c6820fe">

MacOS Sonoma 14.2.1
VSCode: 1.85.1
F5 Extension v3.15.1
TMOS: 17.1.1.1

Br Andréas

**Comment by DumpySquare** [comment]
Hi @andreasforseth , did the latest version fix your issue?
