### ISSUE TITLE
[BUG] Tenants with . in name do not show

### ISSUE THREAD

**Issue by MicSkr** [f5devcentral/vscode-f5#246]
VSCode 1.86.2
The F5 Extension: 3.16.0

Tenants with . in the tenant name do not list in partition of tool.

Does not show; naming example: t_10.10.10.10  
Does not show; naming example: t_100100
 
Does show; naming example: t_10_10_10_10

**Comment by DumpySquare** [comment]
as3 schema allows this.  working to align
^[A-Za-z][0-9A-Za-z_.-]*$
