### ISSUE TITLE
[BUG] V3.16.x ATC Package management broken

### ISSUE THREAD

**Issue by CarlB-dev** [f5devcentral/vscode-f5#249]
In extension version 3.16.0 and 3.16.1, the ATC Package management function is not functioning properly.

Here is what appears with 3.16.x when you click the carat to expand the ATC versions:
![image](https://github.com/f5devcentral/vscode-f5/assets/44070777/d49f4b5a-1829-417d-aa05-7bce28e195d5)

Here is what appears with the 3.15.1 extension:
![image](https://github.com/f5devcentral/vscode-f5/assets/44070777/6b056171-a980-488a-bed3-7b9430ccd4ba)

**Comment by DumpySquare** [comment]
I suspect this is because of same problem with #255 where the ATC repose have changed their base path.  Should get fixed with #255

**Comment by DumpySquare** [comment]
this should be fixed in the v3.17.0 release that just went out
