### ISSUE TITLE
[BUG] Schema validation is using the wrong path

### ISSUE THREAD

**Issue by VameqFytr** [f5devcentral/vscode-f5#255]
The path being used for *.as3.json validation is still using the AS3 /master/ branch which is deprecated:
(https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json)

The correct version of the latest schema is in the "main" branch:
(https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/main/schema/latest/as3-schema.json)

This causes it to mark anything after 3.45 as invalid.

**Comment by DumpySquare** [comment]
fixed in pending v3.17.0 release
