### ISSUE TITLE
[RFE] Ability to organize F5 Hosts into Folders

### ISSUE THREAD

**Issue by emmanuelgirard** [f5devcentral/vscode-f5#71]
Could be nice to have the ability to organize F5 Hosts into folders.

**Comment by emmanuelgirard** [comment]
Could be nice to have the ability to create folders to organize F5 Hosts connections.

**Comment by DumpySquare** [comment]
Good idea.  I'm gonna have to think about exactly how to implement this.

**Comment by DumpySquare** [comment]
I think this is totally doable from a code perspective.  I see ways to hold the information and get it in the tree.  My concern is gui mgmt.  I'm having trouble thinking about how users can/will add/delete folders/devices and potentially to moves in the view it'self without having to modify the underlying JSON.  Do you think it's acceptable to not have those features included (the moves)?

Another thought I had, was to turn everything into a directory with files.  Then it could be treated as such, mostly, in the way that folders and devices would be treated like folder/files that could be dragged and dropped accordingly.  that kinda opens a whole other slew of issues.

**Comment by DumpySquare** [comment]
I haven't forgotten about this one.  Just having trouble working out all the use cases and which ones to support first

**Comment by ghalevy** [comment]
@DumpySquare Any new thoughts?

**Comment by DumpySquare** [comment]
complete, pending release in 3.7

as an initial release, the folder designation must be set in the config file.  Use the gear icon at the top of the view, then edit the config file, save (should hot refresh now)

![image](https://user-images.githubusercontent.com/3260966/159036388-586969c8-324d-437c-8fd2-5cd14516f739.png)
