### ISSUE TITLE
[RFE] seed setup of hosts/devices

### ISSUE THREAD

**Issue by DumpySquare** [f5devcentral/vscode-f5#80]
User would like to provide a device list to get populated at launch.  

This mainly fits in with automated ephemeral environments built with automation tools.  As part of their build (which includes deployed devices, IP addresses, accounts and passwords), they can output a seed file that includes the necessary information to have the device auto-populated in the vscode extension.

This has been talked about in the past and seems like a nice integration and could really smooth out the flow in cloud environments, especially with things like code-server.

At a high level, I'm thinking something like a seed file that the automation tool could leave in the directory.  Something like a .gitignore or .vscode.  

On start up, the extension could check that a workspace is opened, then if the file is there, if found, present the user with a prompt to import.  Also put in a setting to auto-accept-import whenever the file is found.

As part of the process we could also inject the passwords to the password store so that is taken care of in the process.... seamless....

**Comment by mjmenger** [comment]
I was thinking something like https://www.npmjs.com/package/dotenv when I mentioned it.

**Comment by GBond** [comment]
This is definitely, a nice idea as long as there is an emphasis that the users' code repo is the "source of truth" in a migration context (maybe that is emphasized in the Docs/README).

**Comment by DumpySquare** [comment]
This is complete and documented.  Pending next release
