### ISSUE TITLE
[RFE] BZ ID 876281

### ISSUE THREAD

**Issue by walterk82** [f5devcentral/vscode-f5#82]
Please consider implementing internal BZ ID 876281 with this project.
 Thank-you.

**Comment by bitwisecook** [comment]
looks like we really should get around to merging my https://github.com/bitwisecook/vscode-iRule / https://github.com/bitwisecook/vscode-iApp over

**Comment by DumpySquare** [comment]
Thanks @walterk82 , it seems like your asking for irule and irulelx support within the vscode extension.  If that is correct, I believe that @bitwisecook and I probably have most of what you are looking for.  

This vscode extension is mainly focused on REST API handing, so it does have the ability to get/modify/delete irules and iapps.  Combine the API functionality of this extension with the language features of the vscode-irule/iapp extensions and you should have most of what you are asking for. 

https://github.com/f5devcentral/vscode-f5/blob/master/README_docs/tcl.md 

We are looking for a better way to get the latest schema, when released, if you want to have a side conversation about that.

I believe the only thing outstanding, would be irules-lx, of which I can add to the backlog and start looking into what it's gonna take to accommodate that.   Is there a pressing need or is this just a nice to have?

**Comment by walterk82** [comment]
Ah, yes you are correct.  But the number of extensions is a bit confusing.  There should just be 1 F5 extension with customizations available to turn features on/off.  The BZ ID was only referenced as all of the TCL / iRule validation logic exists on box, but that is not a proper development environment.  So, someone should be able to externalize this package at build time and publish on github for consumers to use in VS.Code.  It was the intent since that it is already JavaScript it should be able to more easily be consumed in VS.Code.

**Comment by DumpySquare** [comment]
Thanks @walterk82, can you reach out to me directly?  I'd like to discuss more offline.  Ben Gordon (b.gordon@f5.com)

**Comment by DumpySquare** [comment]
I think the core of this issue stems from different extensions providing different pieces of the functionality and being developed by different people.  While the message may not be clear across everything, the iRule/iApp language functionality is handled by those two extensions.  This extension handles object mgmt through get/post/update of  iRule/iApp objects.

@bitwisecook and I will continue conversations on the future of all this functionality and how we can make it more clear in the future
