### ISSUE TITLE
AS3 with BIG-IQ, vscode exposes all the tenants device the user double click on instead of the one selected

### ISSUE THREAD

**Issue by rjouhann** [f5devcentral/vscode-f5#89]
When using AS3 on BIG-IQ, if a user clicks on a tenant to expose its content, it will open all the AS3 tenants from the BIG-IP and not only the tenant selected.
When using AS3 on BIG-IP, it exposes only the tenant the user double click on.

Behavior should be similar when using AS3 on BIG-IQ. 

![image](https://user-images.githubusercontent.com/25542366/98734113-5d099200-2356-11eb-97cf-c39db92b36e7.png)

@meverett1167

**Comment by DumpySquare** [comment]
Gathering information to get this working

**Comment by DumpySquare** [comment]
I got this working, but discovered that none of the right click options work for bigiq either.  This is going to require a rework of how the data is handled for AS3 for both bigip and bigiq to make sure we have the necessary feature parity.  This work also hinges on some core refactoring that is in progress.  So, in short, this is in progress, but it's going to take a bit longer as we work through other enhancements and refactoring at the same time.    Keep an eye out for the next release!

**Comment by DumpySquare** [comment]
this should all be working with v2.10
