### ISSUE TITLE
What is the replacement for F5 FAST? it is no longer in the vscode market place?

### ISSUE THREAD

**Issue by Kojo101** [f5devcentral/vscode-f5#94]

**Comment by DumpySquare** [comment]
This is the new version of vscode-f5-fast.  The project moved to the DevCentral GitHub organization, got renamed to "vscode-f5" or "The F5 Extension" and republished  to the marketplace, both Microsoft and Open VSC marketplaces.

Please uninstall the old and install the new extension "The F5 Extension".

Check out the new README for the details:  https://github.com/f5devcentral/vscode-f5/blob/main/README.md
New documentation site:  https://f5devcentral.github.io/vscode-f5/#/
and Changelog for latest features:  https://github.com/f5devcentral/vscode-f5/blob/main/CHANGELOG.md

Does that answer your question?

**Comment by Kojo101** [comment]
Thanks
