### ISSUE TITLE
Unable to post TS

### ISSUE THREAD

**Issue by walterk82** [f5devcentral/vscode-f5#95]
Since the version from the prior extension, am I unable to get menu options "Post as TS Declaration" to work.  I have my files saved as "telementry_declaration.ts.json"  The command pallet only returns the "F5-TS: Get TS Declaration" option and the content menu is greyed out.

I am using vscode 1.52.1 and vscode-f5 2.8.2

**Comment by DumpySquare** [comment]
I've been trying to clean up some of the menu's by moving commands to context sensitive right-click menus in the editor.

Looks like I might have had a minor typo.  Can you install DO and see if you are able to access the command via right-click in editor?

if not, can you provide a screenshot?

**Comment by walterk82** [comment]
Unfortunately, I can't use DO on a vCMP guest.  I have screen grabs, but I can't get them to attach to this github issue.  Maybe it's my web filters.

**Comment by DumpySquare** [comment]
Still got my email?  Want to send them directly?

**Comment by walterk82** [comment]
You should have an email by now.

**Comment by DumpySquare** [comment]
Yup.  That's a bug.  Sorry.  Only way to get around it for now is to install DO on the device and it will enable that command.

I have it fixed in dev, but it's gonng be the new year before I get a next release out.

**Comment by walterk82** [comment]
OK, at least I'm not crazy.  Since it's TS, using PostMan is just as fine for now.

**Comment by DumpySquare** [comment]
this is fixed in v2.10
